= OpenRewrite - demo

:toc:

This is a sample project to showcase some of the functionalities of https://https://docs.openrewrite.org/[OpenRewrite]

OpenRewrite allows us to do major refactorings on our source code using (prewritten) recipes.
It works my by making changes to the https://docs.openrewrite.org/concepts-explanations/lossless-semantic-trees[Lossless Semantic Trees] representing our source code and printing the modifications back to the source code/diffs which we can then compare and commit if we deem them ok.

'''

== How to use

OpenRewrite can be run using the Maven/Gradle build plugin tools, or directly from a java main method of a build tool plugin isn't possible (https://docs.openrewrite.org/running-recipes/running-rewrite-without-build-tool-plugins[see for reference])

Both for Maven and Gradle we can run the migrations either by modifying our build files, or by running a shell command or init script respectively.

=== Maven

If we add the plugin to our pom.xml file

[source]
----
<plugin>
  <groupId>org.openrewrite.maven</groupId>
  <artifactId>rewrite-maven-plugin</artifactId>
  <version>5.3.1</version>
</plugin>
----

=== Gradle

For Gradle we need to be certain that mavenCentral() is present in our repositories section, then we need to add the following to our build file:

[source]
----
plugins {
    id 'org.openrewrite.rewrite' version '6.1.16'
}

repositories {
  // needed to resolve recipe artifacts
  mavenCentral()
}

rewrite {
    // here we'll place the recipes we wish to use
}
----

After which we can try `./mvnw rewrite:discover` or `./gradlew rewriteDiscover` to discover which recipes we can run from OpenRewrite using this setup. (we can add other sources/write our own).