= OpenRewrite - demo

:toc:

This is a sample project to showcase some of the functionalities of https://https://docs.openrewrite.org/[OpenRewrite]

OpenRewrite allows us to do major refactorings on our source code using (prewritten) recipes.
It works my by making changes to the https://docs.openrewrite.org/concepts-explanations/lossless-semantic-trees[Lossless Semantic Trees] representing our source code and printing the modifications back to the source code/diffs which we can then compare and commit if we deem them ok.

'''

== Setup

OpenRewrite can be run using the Maven/Gradle build plugin tools, or directly from a java main method of a build tool plugin isn't possible (https://docs.openrewrite.org/running-recipes/running-rewrite-without-build-tool-plugins[see for reference])

Both for Maven and Gradle we can run the migrations either by modifying our build files, or by running a shell command or init script respectively.

=== Maven

If we add the plugin to our pom.xml file

[source]
----
<plugin>
  <groupId>org.openrewrite.maven</groupId>
  <artifactId>rewrite-maven-plugin</artifactId>
  <version>5.3.1</version>
</plugin>
----

=== Gradle

For Gradle we need to be certain that mavenCentral() is present in our repositories section, then we need to add the following to our build file:

[source]
----
plugins {
    id 'org.openrewrite.rewrite' version '6.1.16'
}

repositories {
  // needed to resolve recipe artifacts
  mavenCentral()
}

rewrite {
    // here we'll place the recipes we wish to use
}
----

After which we can try `./mvnw rewrite:discover` or `./gradlew rewriteDiscover` to discover which recipes we can run from OpenRewrite using this setup. (we can add other sources/write our own).

== Usage

=== Adding a recipe without configuration

Some OpenRewrite recipes require some configuration, but we'll start easy with a standard OpenRewrite which doesn't need any setup.

For example if you have a project with a lot of unused imports you can use the `org.openrewrite.java.RemoveUnusedImports` recipe which is part of the core library.

==== Maven
a) run `mvn -U org.openrewrite.maven:rewrite-maven-plugin:run -Drewrite.activeRecipes=org.openrewrite.java.RemoveUnusedImports`

b) add `<recipe>org.openrewrite.java.RemoveUnusedImports</recipe>` to the `<activeRecipes>` in your pom file and perform `./mvnw rewrite:run`

==== Gradle

Add `activeRecipe("org.openrewrite.java.RemoveUnusedImports")` and perform `./gradlew rewriteRun`

If we were to run this one on the current project, and then execute a `git diff` we'd see:

[source]
----
diff --git a/src/main/java/dev/simonverhoeven/openrewritedemo/OpenrewritedemoApplication.java b/src/main/java/dev/simonverhoeven/openrewritedemo/OpenrewritedemoApplication.java
index d97b878..8e85aaf 100644
--- a/src/main/java/dev/simonverhoeven/openrewritedemo/OpenrewritedemoApplication.java
+++ b/src/main/java/dev/simonverhoeven/openrewritedemo/OpenrewritedemoApplication.java
@@ -3,8 +3,6 @@ package dev.simonverhoeven.openrewritedemo;
 import org.springframework.boot.SpringApplication;
 import org.springframework.boot.autoconfigure.SpringBootApplication;

-import java.math.BigDecimal;
-
 @SpringBootApplication
 public class OpenrewritedemoApplication {
----

=== Adding a recipe with a configuration

Some recipes require a configuration. Let's start with an easy one.
Say your organisation changes name, and suddenly you need to rewrite your package names.

For this we can use the `org.openrewrite.java.ChangePackage` recipe.

To set it up we'll need to create a `rewrite.yml`  in which we'll define a recipe name, optionally a display name and the recipe list with the parameters.
In this case we'll be renaming `dev.simonverhoeven.openrewritedemo.oldorgname` to `dev.simonverhoeven.openrewritedemo.neworgname`

[source]
----
---
type: specs.openrewrite.org/v1beta/recipe
name: dev.simonverhoeven.sampleRecipe
displayName: A simple recipe
recipeList:
  - org.openrewrite.java.ChangePackage:
      oldPackageName: dev.simonverhoeven.openrewritedemo.oldorgname
      newPackageName: dev.simonverhoeven.openrewritedemo.neworgname
      recursive: null
----

Then we'll add `dev.simonverhoeven.sampleRecipe` to our active recipes.

When we then run the rewrite we'll see that our `oldorgname` has been renamed to `neworgname` and that the package statement in our `Sample` file has also been adapted.

== References
https://docs.openrewrite.org/recipes[Recipe catalog]