name: CI
on: [ push ]
jobs:
  build:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: set-up-jdk
        uses: actions/setup-java@v2.3.0
        with:
          java-version: "8"
      - name: build
        run: ./gradlew build test